### ISSUE TITLE
Make async default

### ISSUE THREAD

**Issue by andrewbanchich** [nats-io/nats.rs#101]
Other network related crates I've seen, like `reqwest`, had a dedicated `async` module in the early days with everything else being sync, then switched it around so the default is async with a `blocking` module.

Any thoughts on making async the default for NATS?

**Comment by stjepang** [comment]
Well, I think there is no right or wrong choice on what should be the default. And it also probably doesn't matter much :)

The first version of the NATS client was blocking so we kept that as the default and then added async API on top of it. And the reverse is true for `reqwest` - it has always been async but then it also offers a blocking API on top of it.

Since the standard library is blocking and it's much easier to get started with blocking APIs than anything async, my feeling is that blocking APIs should be in the spotlight, while async APIs should be provided alongside them as an 'addition'. That's the rationale for why we have `asynk` module rather than `blocking`.

**Comment by andrewbanchich** [comment]
Sounds good! That's obviously up to you, but my initial feeling regarding this was `std` is blocking by default because it isn't centered around IO, while crates like `reqwest` / `nats` would be async by default since they are all IO, and especially for a use case like NATS which is high performance messaging, I would assume most users would be using async.

But again, just weighing in my own thoughts on this, and it doesn't really matter much. Feel free to close 😄

**Comment by stjepang** [comment]
Makes sense! Honestly, I'm feeling pretty ambivalent on all this. Thanks for sharing thoughts, will think about this a bit more later :)
