### ISSUE TITLE
Durable connections support

### ISSUE THREAD

**Issue by avkonst** [nats-io/nats.rs#105]
#### Use Case:

As far as I understand Nats supports at least once delivery guarantee and allows to subscribe from a given offset sequence number. I can not find this capability in the rust client.

#### Proposed Change:

Add support for durable connections, at least once delivery guarantee and streaming from a given offset

#### Who Benefits From The Change(s)?

Rust applications

#### Alternative Approaches

Have not found, except switching to kafka

**Comment by stjepang** [comment]
Related to: #95

**Comment by derekcollison** [comment]
Plain NATS clients can participate in JetStream, our builtin persistence engine that is in nightly builds of the server and is in the next release.

https://github.com/nats-io/jetstream

We will be adding some syntactic sugar to the base clients but they can be used today as is..

**Comment by andrewbanchich** [comment]
The main aspect of this I'm interested in with #95 is being able to process messages concurrently. From what I understand, in order to use JetStream from nats.rs we need to use req / rep to make requests to `$JS.API.CONSUMER.MSG.NEXT.SOME_STREAM.SOME_CONSUMER`. It's easy to do that serially, but I need to be able to process messages as fast as possible, so it would be ideal if we could have a `futures::Stream` of `nats::asynk::Message`s so we can use something like `futures::stream::StreamExt::for_each_concurrent` to process N messages at a time.

So far I haven't found a good way to use the req / rep APIs to construct a `futures::Stream`.

**Comment by derekcollison** [comment]
Theoretically you can do concurrent processing, JetStream consumers can be pull or push based, your choice. However how that  fits into Rust and possibly async that is best left for @stjepang to weigh in on..

**Comment by andrewbanchich** [comment]
Any thoughts on implementing a Stream for pull-based message consumption @stjepang ?

**Comment by derekcollison** [comment]
Yes that will be part of the work to have some syntactic sugar around JetStream for the Rust client.

https://github.com/nats-io/jetstream/

**Comment by spacejam** [comment]
replaced by https://github.com/nats-io/nats.rs/issues/137
