### ISSUE TITLE
Compilation error when using async-nats as a library (related: tokio-rustls, rustls)

### ISSUE THREAD

**Issue by nickgerace** [nats-io/nats.rs#1090]
### NATS version

0.31.0

### rustc version

rustc 1.70.0 (90c541806 2023-05-31)

### OS/Container environment

macOS 13.5

### Steps or code to reproduce the issue

1. Use version `0.31.0`
2. See that  `rustls` version `0.21.1` is being used instead of a newer version that provides the missing method below
3. Observe the following error:

```
error[E0599]: no method named `with_client_auth_cert` found for struct `ConfigBuilder` in the current scope
--
  | --> third-party/rust/async-nats-0.31.0.crate/src/tls.rs:117:29
  | \|
  | 117 \|                     builder.with_client_auth_cert(cert, key).map_err(\|_\| {
  | \|                             ^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `with_no_client_auth`
```

### Expected result

Success compilation.

### Actual result

The error observed above.

**Comment by paulocsanz** [comment]
From my understanding what is going on here is that `async-nats` is using `tokio-rustls` which pins `rustls` to `0.21.0`.

But `async-nats` is using a feature from `rustls` that exists in `0.21.6` but not in `0.21.0`.

Since it's a minor version bump, rust seems ok to sometimes use the latest version instead of the one pinned, that's why this project compiles in some environments.

There was something going on in our enviroment, a different dependency using rustls `0.21.1`, so rust didn't update it to `0.21.6` when installing `async-nats`, because it didn't "need" to.

If `async-nats` wants to use a feature from a `rustls` version that's not _exactly_ the one pinned in cargo toml, it has to add the dependency, so adding `rustls = "0.24.6" to the cargo toml and releasing a new version.

We added this line to our cargo toml and it fixed it, but the issue originates from this repo.

**Comment by paolobarbolini** [comment]
> We added this line to our cargo toml and it fixed it, but the issue originates from this repo.

FYI if you're making a binary crate you can do `cargo update -p rustls`. It won't invalidate everything else you said bu tat least you won't need to add a line in `Cargo.toml`

**Comment by nepalez** [comment]
It should be fixed here https://github.com/nats-io/nats.rs/pull/1108

**Comment by barafael** [comment]
@nickgerace can this issue be closed?

**Comment by nickgerace** [comment]
I believe so!
