### ISSUE TITLE
Add possibility to check count of pending messages and bytes

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [nats-io/nats.rs#123]
#### Use Case:
I want to track on client side, how many messages and/or bytes (but I mostly interested in message count) are pending. It's required for making a decision, when I need to add more consumers (some kind of manually written auto-scaling)
#### Proposed Change:
Add some kind of API for getting pending message count and pending bytes.
#### Who Benefits From The Change(s)?
At least me :) However, such feature will be usefil for any developer.
#### Alternative Approaches
I don't know.

**Comment by andrewbanchich** [comment]
@spacejam I think you might have accidentally referenced this issue instead of #124 in the latest release?

**Comment by spacejam** [comment]
@ZaMaZaN4iK I don't believe that this is a metric that will signify anything about consumer behavior, because the local client is decoupled from any consumers by the nats server. Any pending bytes that have not yet been sent to the server are more likely to be indicative of network functionality between the nats client and the nats server, rather than anything happening with subscribers. Jetstream may enable this desired workflow for you better than plain NATS, as it supports [getting information about consumer progress](https://github.com/nats-io/jetstream/#advisories).
