### ISSUE TITLE
Stream over subscription

### ISSUE THREAD

**Issue by abdelmonem17** [nats-io/nats.rs#138]
Is there a way to build a stream over nats client subscription ?
I tried to build a stream using functions supplied for subscription like example below but I find that is very wasteful for pc resources.
 
```
impl Stream for NatsStream
{
    type Item = Message;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {

        let mut guard=self.state.lock().unwrap();

        match &guard.state
        {
            State::Ready=> {
                guard.state = State::Waiting;
                return Poll::Ready(guard.data.clone());
            },
            State::Waiting=> {
                guard.waker = Some(cx.waker().clone());
                return Poll::Pending;

            },
            _=> {
                guard.state = State::Pending;
                return Poll::Ready(None);
            }


        }

    }
}
```

**Comment by andrewbanchich** [comment]
Related: https://github.com/nats-io/nats.rs/issues/122#issuecomment-758083298

**Comment by abdelmonem17** [comment]
Thank you for your great effort in developing library but next function uses a blocking technique so it will limit the usage of the library or you have to workaround anyway will lead to less performance.

**Comment by stjepang** [comment]
Here's how you can use `futures::stream::unfold()` to create a stream:

```rust
use futures::{executor, prelude::*, stream};

fn main() -> std::io::Result<()> {
    executor::block_on(async {
        let nc = async_nats::connect("localhost:4222").await?;
        let sub = nc.subscribe("subject").await?;

        let mut s = stream::unfold(sub, |sub| async {
            sub.next().await.map(|msg| (msg, sub))
        })
        .boxed(); // you can also use futures::pin_mut!() instead of boxed()

        let msg = s.next().await;

        Ok(())
    })
}
```

We decided to avoid the `Stream` trait because it's on track to be moved from the `futures` crate into the standard library relatively soon (will take several months at least).

Furthermore, Tokio 1.0 decided to leave this trait out completely and suggests using [`tokio-stream`](https://docs.rs/tokio-stream/) instead as a stopgap solution (I believe this crate will be deprecated when `Stream` gets stabilized). Even types like [`TcpListener`](https://docs.rs/tokio/1.0.1/tokio/net/struct.TcpListener.html) don't implement `Stream` anymore. If you're using Tokio, relying on the `Stream` trait will be a painful experience for the time being.

> next function uses a blocking technique so it will limit the usage of the library or you have to workaround anyway will lead to less performance.

True -- it's not optimal right now (although pretty fast in our benchmarks) but we'll remove blocking from the `next()` function and keep optimizing this...

**Comment by spacejam** [comment]
@abdelmonem17 async will almost always result in significantly worse performance than just using threads in a principled manner, so if this is important for you, I would strongly recommend avoiding the entire async ecosystem.

**Comment by andrewbanchich** [comment]
@spacejam Are you saying that only in regard to NATS due to some kind of NATS-specific behavior? Using async has a great deal of performance benefits when dealing with network IO, even when using threads. I would think when using something like NATS that is a high performance, network IO based tool that async would be hugely beneficial over native threads.

What am I misunderstanding here? It just seems that statement is the opposite of what I would expect.

**Comment by abdelmonem17** [comment]
> Here's how you can use `futures::stream::unfold()` to create a stream:
> 
> ```rust
> use futures::{executor, prelude::*, stream};
> 
> fn main() -> std::io::Result<()> {
>     executor::block_on(async {
>         let nc = async_nats::connect("localhost:4222").await?;
>         let sub = nc.subscribe("subject").await?;
> 
>         let mut s = stream::unfold(sub, |sub| async {
>             sub.next().await.map(|msg| (msg, sub))
>         })
>         .boxed(); // you can also use futures::pin_mut!() instead of boxed()
> 
>         let msg = s.next().await;
> 
>         Ok(())
>     })
> }
> ```
> 
> We decided to avoid the `Stream` trait because it's on track to be moved from the `futures` crate into the standard library relatively soon (will take several months at least).
> 
> Furthermore, Tokio 1.0 decided to leave this trait out completely and suggests using [`tokio-stream`](https://docs.rs/tokio-stream/) instead as a stopgap solution (I believe this crate will be deprecated when `Stream` gets stabilized). Even types like [`TcpListener`](https://docs.rs/tokio/1.0.1/tokio/net/struct.TcpListener.html) don't implement `Stream` anymore. If you're using Tokio, relying on the `Stream` trait will be a painful experience for the time being.
> 
> > next function uses a blocking technique so it will limit the usage of the library or you have to workaround anyway will lead to less performance.
> 
> True -- it's not optimal right now (although pretty fast in our benchmarks) but we'll remove blocking from the `next()` function and keep optimizing this...

unfortunately I try this solution and others like this and these all fails in my use case,
I suggest that you can give stream over subscription by returning a copy of the Receiver<Message> using a function and it is already implement Stream trait.

**Comment by spacejam** [comment]
@andrewbanchich async implementations tend to do 2x+ the number of syscalls, increase cache misses, increase branch mispredictions, increase memory usage, increase latency, reduce throughput, and significantly reduce programmer effectiveness due to additional bug classes that become possible only when using async. I have never measured any benefit in a real system I've worked on, only surprisingly significant performance hits due to the costs imposed by forcing everything through the hyper-minimal executor interface. Feel free to follow up over email, rather than this thread, as this is a bit of a tangent.

**Comment by stjepang** [comment]
> Unfortunately I tried this solution and others like this but these all fails in my use case,

Can you perhaps elaborate a bit about your use case? I'm confused because it's not obvious to me why this wouldn't work...

**Comment by abdelmonem17** [comment]
> > Unfortunately I tried this solution and others like this but these all fails in my use case,
> 
> Can you perhaps elaborate a bit about your use case? I'm confused because it's not obvious to me why this wouldn't work...

Thank you for help anyway I did workaround and it worked.
