### ISSUE TITLE
async-nats missing features

### ISSUE THREAD

**Issue by andrewbanchich** [nats-io/nats.rs#158]
I noticed not all features of `nats` are there for `async-nats` ([request_timeout](https://docs.rs/nats/0.9.7/nats/struct.Connection.html#method.request_timeout) for example).

**Comment by spacejam** [comment]
Async functionality will always be a bit of a whack-a-mole game. however, if you look at the implementation, pretty much everything in the async crate is just a simple wrapper aroudn the sync version using [`unblock`](https://docs.rs/blocking/1.0.2/blocking/fn.unblock.html). We found that a sync core was significantly higher throughput than using async, due to avoiding the scheduling overhead induced by async schedulers.

**Comment by abdelmonem17** [comment]
@spacejam You are right about async  has an overhead but why you don't give the user of the library the choices if he want to use async or block_on it by himself.

**Comment by abdelmonem17** [comment]
In my case I had to workaround to use Subscription::next but I would be easy to use async next and more performance

**Comment by spacejam** [comment]
Users can use everything in the sync crate from async by wrapping the various functions in `unblock`, which is how the async crate itself accesses the core functionality. If this does not work for you, then feel free to open a PR to add your desired functionality to the async crate.

**Comment by andrewbanchich** [comment]
If that's the plan, why not just remove the async crate altogether and have users do that?

**Comment by spacejam** [comment]
That would result in a steady stream of issues being opened requesting async support, as is the case with other crates I maintain, so I don't believe that would actually reduce the maintenance burden. I'm happy to maintain the async usability layer which reduces those issues being opened, but the community should open PR's adding support for the specific things that they want to use for async.
