### ISSUE TITLE
The publish method loses 2 messages after a disconnection from the NATS server

### ISSUE THREAD

**Issue by DamianoChini** [nats-io/nats.rs#182]
#### NATS version
name = "async-nats"
version = "0.9.16"

#### rustc version (`rustc --version` - we support Rust 1.41 and up)
rustc 1.51.0

#### OS/Container environment:
Fedora release 31 (Thirty One)

Docker for the NATS server 

#### Steps or code to reproduce the issue:
1. Create a client connection to a running NATS server
2. Stop the NATS server
3. Publish 3 messages to the NATS server
4. Restart the NATS server

#### Expected result:
I expect that after restarting the NATS server, the server receives 3 messages from the client.
Alternatively, I expect that an error is returned when the publishing fails.

#### Actual result:
The NATS server after the restart receives only the third message. The first 2 are never delivered.
The (async) NATS client returns `Ok()` for all the 3 messages, so we can not handle the messages which are not correctly published.

#### Additional details
Trying to understand when the publish fails, we also tried to `.flush().await` after every `.publish(subject, msg).await`. The flush returns an error for the first message, but for the second message it hangs until the connection with the NATS server is restored (returning `Ok()` but without delivering the message to the server). As an example please see the simplified code below.
Also the `flush_timeout()` method hangs until the connection with the NATS server is restored, without returning any error after the timeout duration expires.
```
connection.publish(subject, &msg1).await; // --> Returns Ok()
connection.flush().await; // --> Returns Err(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })

connection.publish(subject, &msg2).await; // --> Returns Ok()
connection.flush().await; // --> Hangs until connection is restored, returning Ok() but without delivering msg2

connection.publish(subject, &msg3).await; // --> Returns Ok()
connection.flush().await; // --> Hangs until connection is restored, returning Ok() and delivering msg3
```

**Comment by DamianoChini** [comment]
Hello!
We saw that the first 2 messages are not lost anymore if we reset the client writer to `None` upon disconnection, in particular where the `disconnect_callback` is called [https://github.com/nats-io/nats.rs/blob/master/src/client.rs#L546](url)
```
connector.get_options().disconnect_callback.call();
self.state.write.lock().writer = None;
```
Could this solution be acceptable for you?

**Comment by spacejam** [comment]
Thanks for opening this issue, @DamianoChini! The reason why this didn't get caught in the correctness tests is because it's not actually a violation of any nats correctness guarantees, since nats is at-most-once delivery. While it's not a correctness issue, it is a performance issue, so I'll fix this and cut a new release that includes the fix today.

To clarify the correctness situation: when a disconnect happens, everything in the outgoing message buffer gets thrown away. In your case, flush happens after connectivity has been restored, but also after the outgoing message buffer has been thrown away, so the flush is just telling you "yes, we are able to receive a response from the server, but we might have experienced issues in the past and we might experience issues in the future." Flush, as well as fs primitives like fsync, don't necessarily communicate "all previous operations have been successful" but rather "at least one operation was successful, namely the sync operation itself". This fsync behavior caused a lot of confusion even by authors of the postgres database... 

Anyway, the main takeaway is that nats is at-most-once delivery by default, and if you want at-least-once, you should use jetstream or implement your own reliable messaging protocol on top.

**Comment by spacejam** [comment]
Version 0.9.18 has been published which includes your fix. Thank you!

**Comment by DamianoChini** [comment]
Thank you a lot, also for the explanation!
