### ISSUE TITLE
Adding CAs from string rather than file

### ISSUE THREAD

**Issue by dev-mull** [nats-io/nats.rs#204]
Due to deployment concerns and a pki mess, I have my root ca compiled into my app, not in a separate file on disk.

I looked but I could not find a way to manually setup the tls config. In the go client I am able to do this via tls.Config.

**Comment by spacejam** [comment]
Hey @dev-mull, thanks for opening this issue. I've added a new method to `nats::Options` which allows manually providing a `rustls::ClientConfig` for use when connecting to the nats server. Note that this method will keep key material in memory across connections and won't zero key material that is stored in memory as is done normally. This will let you fine-tune any TLS-related configurables to the fullest extent that our backing rustls dependency allows. To avoid rustls version collision issues that may arise due to using other rustls versions in your own crates, I have re-exported the version of rustls that this crate uses at `nats::rustls`.

https://github.com/nats-io/nats.rs/pull/205

I expect to release this a little later today.

Please let me know if you have any other friction with this and I'll try to improve the documentation or functionality to let you be productive.
