### ISSUE TITLE
Remove redundant allocations

### ISSUE THREAD

**Issue by YaZasnyal** [nats-io/nats.rs#889]
`try_read_op` contains several places with conversion to `Vec` that can be replaced to something like the code below. 

https://github.com/nats-io/nats.rs/blob/405fced46dcdc5bac32e1fd098b166ca9aaff005/async-nats/src/connection.rs#L102-L120

Can be replaced with something like this:
```rust
            let mut it = args.into_iter();
            let subject = it.next();
            let sid = it.next();
            let mut reply_to = it.next();
            let mut payload_len = it.next();
            if payload_len.is_none() {
                std::mem::swap(&mut reply_to, &mut payload_len);
            }

            if subject.is_none() || sid.is_none() || payload_len.is_none() || it.next().is_some() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "invalid number of arguments after MSG",
                ));
            }
```

If this code is acceptable I can open a new MR applying this change to `HMSG` as well.

**Comment by YaZasnyal** [comment]
Also `write_op` gets operation by value. This is why some additional allocations have to be made for `subject`, `respod_to` and headers. If this function will accept reference to the operation it won't be necessary anymore. I have checked and it probably can be done.

https://github.com/nats-io/nats.rs/blob/405fced46dcdc5bac32e1fd098b166ca9aaff005/async-nats/src/lib.rs#L582-L601

If you are interested in this I can open a MR.

**Comment by YaZasnyal** [comment]
And one more. If we can change the API of the `Message` to handle `subject` as `Bytes` one more allocation can be removed. But I am not sure that it will be comfortable to use.

**Comment by YaZasnyal** [comment]
Opened MRs for the first two. 

I also think that the subject to `publish` (and possibly others) should be `Bytes` as well. Bytes can be cheaply created from `String`, `Vec[u8]`, boxed arrays and so on. But most importantly it is essentially free for `'static` strings when the topic is known at compile time and can be cached on the caller side allowing to copy it without allocation.

**Comment by Jarema** [comment]
@YaZasnyal that's for all your contributions and insights!

We definately want to improve on `subject`, though that is not as straightforward as it may seem.

Sometimes, even if user passes `'static`, we might need to allocate. Especially if that is a reply subject. Sure, `Bytes` would handle both cases, but it what I dislike in that pattern that we are not honest or informative to the users what allocates and what not.
That's why we discussed `AsSubject` and `IntoSubject`, which would make our intent clear. Internally, they would both probably use `Bytes`.

Additionally, such an approach would allow for a nice way to validate subjects. @MattesWhite put a lot of effort into that approach. I think we should resume the effort soon, in the most lightweight form possible.

**Comment by YaZasnyal** [comment]
I think this one can be closed now.
